apiVersion: v2
name: zeta-prompt-library
description: Helm chart to deploy Zeta Prompt Library - AI prompt curation platform
version: 0.1.2-SNAPSHOT
icon: https://prompts.chat/favicon/apple-touch-icon.png
appVersion: 0.1.1
type: application
dependencies:
- name: common
  version: 1.0.121
  repository: '@chartrepo'
