/**
 * Campaign DAG Engine — Campaigns as first-class objects with nested
 * workflows, lineage, and approval state.
 *
 * 12-month workflow-moat target. A Campaign is the top-level planning
 * unit a CMO/VP-Marketing interacts with. Each campaign contains one or
 * more workflow runs (already tracked by marketing-api), plus a
 * directed-acyclic graph of dependencies so we can show real campaign
 * lineage ("this blog post came from this whitepaper, generated by this
 * agent on this date, approved by that user").
 *
 * v1 scope (this file):
 *   - Create/update campaigns and link workflow runs.
 *   - Add typed asset nodes (brief, blog, ad, email, post, creative)
 *     with parent/child edges.
 *   - Search by tag, persona, skill, user, approval-state.
 *   - Persistence via registerStore (file-backed or Postgres).
 *
 * Intentionally decoupled from marketing-api so that Product/Engineering
 * personas can reuse this later.
 *
 * @author Phani Marupaka <https://linkedin.com/in/phani-marupaka>
 * @copyright © 2026 Phani Marupaka. All rights reserved.
 */

import { registerStore } from './gateway-persistence.js';

export type AssetType =
  | 'brief'
  | 'outline'
  | 'blog'
  | 'ad'
  | 'email'
  | 'post'
  | 'landing_page'
  | 'creative'
  | 'research'
  | 'other';

export type CampaignStatus = 'draft' | 'active' | 'paused' | 'completed' | 'archived';

export interface CampaignAsset {
  id: string;
  campaignId: string;
  type: AssetType;
  title: string;
  /** Storage reference — file path, URL, or inline doc ID. */
  ref?: string;
  content?: string;           // inline asset preview
  producedBy?: string;        // agent or user id
  sourceExecutionId?: string; // marketing execution this came from
  skillId?: string;
  /** Directly-derived-from references. Used to build the DAG. */
  parents: string[];
  approved: boolean;
  approvedBy?: string;
  approvedAt?: string;
  tags: string[];
  createdAt: string;
  updatedAt: string;
}

export interface Campaign {
  id: string;
  name: string;
  description?: string;
  owner: string;
  status: CampaignStatus;
  targetAudience?: string;
  objectives?: string[];
  startDate?: string;
  endDate?: string;
  workflowRunIds: string[];   // marketing execution IDs linked to this campaign
  tags: string[];
  createdAt: string;
  updatedAt: string;
}

const campaigns = new Map<string, Campaign>();
const assets = new Map<string, CampaignAsset>();

registerStore(
  'campaigns',
  () => Array.from(campaigns.values()) as unknown as Record<string, unknown>[],
  (rows) => {
    campaigns.clear();
    for (const r of rows as unknown as Campaign[]) campaigns.set(r.id, r);
  },
);

registerStore(
  'campaign_assets',
  () => Array.from(assets.values()) as unknown as Record<string, unknown>[],
  (rows) => {
    assets.clear();
    for (const r of rows as unknown as CampaignAsset[]) assets.set(r.id, r);
  },
);

// ---------------------------------------------------------------------------
// Campaign CRUD
// ---------------------------------------------------------------------------

export function createCampaign(input: {
  name: string;
  description?: string;
  owner: string;
  status?: CampaignStatus;
  targetAudience?: string;
  objectives?: string[];
  startDate?: string;
  endDate?: string;
  tags?: string[];
}): Campaign {
  const id = `cmp-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
  const now = new Date().toISOString();
  const c: Campaign = {
    id,
    name: input.name,
    description: input.description,
    owner: input.owner,
    status: input.status ?? 'draft',
    targetAudience: input.targetAudience,
    objectives: input.objectives ?? [],
    startDate: input.startDate,
    endDate: input.endDate,
    workflowRunIds: [],
    tags: input.tags ?? [],
    createdAt: now,
    updatedAt: now,
  };
  campaigns.set(id, c);
  return c;
}

export function updateCampaign(id: string, patch: Partial<Campaign>): Campaign | undefined {
  const c = campaigns.get(id);
  if (!c) return undefined;
  const updated = { ...c, ...patch, id: c.id, updatedAt: new Date().toISOString() };
  campaigns.set(id, updated);
  return updated;
}

export function getCampaign(id: string): Campaign | undefined {
  return campaigns.get(id);
}

export function listCampaigns(filter?: {
  owner?: string;
  status?: CampaignStatus;
  tag?: string;
}): Campaign[] {
  let list = Array.from(campaigns.values());
  if (filter?.owner) list = list.filter((c) => c.owner === filter.owner);
  if (filter?.status) list = list.filter((c) => c.status === filter.status);
  if (filter?.tag) list = list.filter((c) => c.tags.includes(filter.tag!));
  return list.sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
}

export function deleteCampaign(id: string): boolean {
  // Cascade: drop all assets for this campaign.
  for (const [aid, a] of assets) if (a.campaignId === id) assets.delete(aid);
  return campaigns.delete(id);
}

/** Link a marketing execution ID to a campaign. */
export function linkExecutionToCampaign(campaignId: string, executionId: string): Campaign | undefined {
  const c = campaigns.get(campaignId);
  if (!c) return undefined;
  if (!c.workflowRunIds.includes(executionId)) c.workflowRunIds.push(executionId);
  c.updatedAt = new Date().toISOString();
  campaigns.set(campaignId, c);
  return c;
}

// ---------------------------------------------------------------------------
// Asset CRUD
// ---------------------------------------------------------------------------

export function addAsset(input: {
  campaignId: string;
  type: AssetType;
  title: string;
  ref?: string;
  content?: string;
  producedBy?: string;
  sourceExecutionId?: string;
  skillId?: string;
  parents?: string[];
  tags?: string[];
}): CampaignAsset {
  if (!campaigns.has(input.campaignId)) {
    throw new Error(`Campaign not found: ${input.campaignId}`);
  }
  const id = `ast-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
  const now = new Date().toISOString();
  const a: CampaignAsset = {
    id,
    campaignId: input.campaignId,
    type: input.type,
    title: input.title,
    ref: input.ref,
    content: input.content,
    producedBy: input.producedBy,
    sourceExecutionId: input.sourceExecutionId,
    skillId: input.skillId,
    parents: input.parents ?? [],
    approved: false,
    tags: input.tags ?? [],
    createdAt: now,
    updatedAt: now,
  };
  assets.set(id, a);
  return a;
}

export function approveAsset(assetId: string, approverId: string): CampaignAsset | undefined {
  const a = assets.get(assetId);
  if (!a) return undefined;
  a.approved = true;
  a.approvedBy = approverId;
  a.approvedAt = new Date().toISOString();
  a.updatedAt = a.approvedAt;
  assets.set(assetId, a);
  return a;
}

export function getAsset(id: string): CampaignAsset | undefined {
  return assets.get(id);
}

export function listCampaignAssets(campaignId: string): CampaignAsset[] {
  return Array.from(assets.values())
    .filter((a) => a.campaignId === campaignId)
    .sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime());
}

/** Full-text-ish search across title, tags, content. Case-insensitive. */
export function searchAssets(query: string, limit = 50): CampaignAsset[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return Array.from(assets.values())
    .filter((a) => {
      return a.title.toLowerCase().includes(q)
        || a.tags.some((t) => t.toLowerCase().includes(q))
        || (a.content?.toLowerCase().includes(q) ?? false);
    })
    .slice(0, limit);
}

/** Given an asset id, return its ancestor chain (BFS upward). */
export function getAssetLineage(assetId: string): CampaignAsset[] {
  const visited = new Set<string>();
  const out: CampaignAsset[] = [];
  const queue: string[] = [assetId];
  while (queue.length > 0) {
    const cur = queue.shift()!;
    if (visited.has(cur)) continue;
    visited.add(cur);
    const a = assets.get(cur);
    if (!a) continue;
    out.push(a);
    for (const p of a.parents) queue.push(p);
  }
  return out;
}

/** Campaign-level dashboard stats for the Marketing Control Tower. */
export function getCampaignStats(campaignId: string): {
  campaign: Campaign | undefined;
  assetCounts: Record<AssetType, number>;
  approvedCount: number;
  pendingCount: number;
  totalRuns: number;
} {
  const c = campaigns.get(campaignId);
  const list = Array.from(assets.values()).filter((a) => a.campaignId === campaignId);
  const assetCounts = {
    brief: 0, outline: 0, blog: 0, ad: 0, email: 0,
    post: 0, landing_page: 0, creative: 0, research: 0, other: 0,
  } as Record<AssetType, number>;
  let approvedCount = 0;
  for (const a of list) {
    assetCounts[a.type] = (assetCounts[a.type] ?? 0) + 1;
    if (a.approved) approvedCount++;
  }
  return {
    campaign: c,
    assetCounts,
    approvedCount,
    pendingCount: list.length - approvedCount,
    totalRuns: c?.workflowRunIds.length ?? 0,
  };
}

/** Cross-campaign summary for the top of the Control Tower page. */
export function getControlTowerSummary(): {
  totalCampaigns: number;
  activeCampaigns: number;
  totalAssets: number;
  totalRuns: number;
  assetsByType: Record<AssetType, number>;
  recentCampaigns: Campaign[];
} {
  const totalCampaigns = campaigns.size;
  const activeCampaigns = Array.from(campaigns.values()).filter((c) => c.status === 'active').length;
  const totalAssets = assets.size;
  let totalRuns = 0;
  for (const c of campaigns.values()) totalRuns += c.workflowRunIds.length;

  const assetsByType = {
    brief: 0, outline: 0, blog: 0, ad: 0, email: 0,
    post: 0, landing_page: 0, creative: 0, research: 0, other: 0,
  } as Record<AssetType, number>;
  for (const a of assets.values()) assetsByType[a.type] = (assetsByType[a.type] ?? 0) + 1;

  return {
    totalCampaigns,
    activeCampaigns,
    totalAssets,
    totalRuns,
    assetsByType,
    recentCampaigns: listCampaigns().slice(0, 5),
  };
}
