/**
 * Marketing Workflows — Gateway copy for API execution
 * Mirrors apps/web marketing-workflows.ts structure for execution.
 * @author Phani Marupaka <https://linkedin.com/in/phani-marupaka>
 * @copyright © 2026 Phani Marupaka. All rights reserved.
 */

export interface WorkflowStepRef {
  id: string;
  order: number;
  name: string;
  agent: string;
  tool?: string;
  outputKey: string;
  requiresApproval?: boolean;
}

export interface WorkflowRef {
  id: string;
  slug: string;
  name: string;
  cluster: string;
  steps: WorkflowStepRef[];
}

// Minimal workflow refs for execution — full definitions live in apps/web
export const MARKETING_WORKFLOW_REFS: WorkflowRef[] = [
  { id: 'wf-001', slug: 'webinar-campaign-generator', name: 'Webinar Campaign Generator', cluster: 'Campaign', steps: [{ id: 's1', order: 1, name: 'Audience & Messaging Strategy', agent: 'Strategy', tool: 'Claude', outputKey: 'strategy' }, { id: 's2', order: 2, name: 'Write Invite Email Series', agent: 'Copy', tool: 'Claude', outputKey: 'email_series' }, { id: 's3', order: 3, name: 'LinkedIn Ad Copy', agent: 'Campaign', tool: 'LinkedIn Ads', outputKey: 'linkedin_ads' }, { id: 's4', order: 4, name: 'Landing Page Copy', agent: 'Copy', tool: 'Claude', outputKey: 'landing_page' }, { id: 's5', order: 5, name: 'Post-Webinar Follow-Up', agent: 'Copy', tool: 'Claude', outputKey: 'followup_emails', requiresApproval: true }] },
  { id: 'wf-002', slug: 'product-launch-campaign', name: 'Product Launch Campaign Builder', cluster: 'Campaign', steps: [{ id: 's1', order: 1, name: 'Launch Messaging Framework', agent: 'Strategy', tool: 'Claude', outputKey: 'messaging' }, { id: 's2', order: 2, name: 'Email Launch Series', agent: 'Copy', tool: 'Claude', outputKey: 'email_series' }, { id: 's3', order: 3, name: 'Landing Page Copy', agent: 'Copy', tool: 'Claude', outputKey: 'landing_page', requiresApproval: true }, { id: 's4', order: 4, name: 'LinkedIn Post Series', agent: 'Copy', tool: 'Claude', outputKey: 'linkedin_posts' }] },
  { id: 'wf-003', slug: 'abm-outreach-campaign', name: 'ABM Outreach Campaign', cluster: 'Campaign', steps: [{ id: 's1', order: 1, name: 'Account Segmentation', agent: 'Research', tool: 'Perplexity', outputKey: 'account_segments' }, { id: 's2', order: 2, name: 'Personalized Messaging', agent: 'Strategy', tool: 'Claude', outputKey: 'personalized_messaging' }, { id: 's3', order: 3, name: 'Outreach Email Templates', agent: 'Copy', tool: 'Claude', outputKey: 'outreach_emails' }, { id: 's4', order: 4, name: 'LinkedIn Message Templates', agent: 'Copy', tool: 'Claude', outputKey: 'linkedin_messages', requiresApproval: true }] },
  { id: 'wf-004', slug: 'paid-media-campaign-pack', name: 'Paid Media Campaign Pack', cluster: 'Campaign', steps: [{ id: 's1', order: 1, name: 'Campaign Strategy', agent: 'Strategy', tool: 'Claude', outputKey: 'campaign_brief' }, { id: 's2', order: 2, name: 'Ad Copy Variants', agent: 'Copy', tool: 'Claude', outputKey: 'ad_copy' }, { id: 's3', order: 3, name: 'Creative Prompts', agent: 'Copy', tool: 'Claude', outputKey: 'creative_prompts' }] },
  { id: 'wf-005', slug: 'multi-channel-campaign-planner', name: 'Multi-Channel Campaign Planner', cluster: 'Campaign', steps: [{ id: 's1', order: 1, name: 'Messaging Matrix', agent: 'Strategy', tool: 'Claude', outputKey: 'messaging_matrix' }, { id: 's2', order: 2, name: 'Channel Plan', agent: 'Campaign', tool: 'Claude', outputKey: 'channel_plan' }, { id: 's3', order: 3, name: 'Creative Checklist', agent: 'Campaign', tool: 'Claude', outputKey: 'creative_checklist' }] },
  { id: 'wf-006', slug: 'nurture-email-sequence', name: 'Nurture Email Sequence Builder', cluster: 'Campaign', steps: [{ id: 's1', order: 1, name: 'Sequence Strategy', agent: 'Strategy', tool: 'Claude', outputKey: 'sequence_strategy' }, { id: 's2', order: 2, name: 'Email Drafts', agent: 'Copy', tool: 'Claude', outputKey: 'email_sequence' }, { id: 's3', order: 3, name: 'Subject Line Variants', agent: 'Copy', tool: 'Claude', outputKey: 'subject_variants', requiresApproval: true }] },
  { id: 'wf-007', slug: 'blog-from-brief', name: 'Blog From Brief', cluster: 'Content', steps: [{ id: 's1', order: 1, name: 'Outline & Structure', agent: 'Copy', tool: 'Claude', outputKey: 'outline' }, { id: 's2', order: 2, name: 'Blog Draft', agent: 'Copy', tool: 'Claude', outputKey: 'blog_draft' }, { id: 's3', order: 3, name: 'SEO Metadata', agent: 'Copy', tool: 'Claude', outputKey: 'seo_metadata' }] },
  { id: 'wf-008', slug: 'blog-from-whitepaper', name: 'Blog From Whitepaper', cluster: 'Content', steps: [{ id: 's1', order: 1, name: 'Extract Key Insights', agent: 'Research', tool: 'Claude', outputKey: 'key_insights' }, { id: 's2', order: 2, name: 'Blog Outline', agent: 'Copy', tool: 'Claude', outputKey: 'outline' }, { id: 's3', order: 3, name: 'Blog Draft', agent: 'Copy', tool: 'Claude', outputKey: 'blog_draft', requiresApproval: true }] },
  { id: 'wf-009', slug: 'blog-series-generator', name: 'Blog Series Generator', cluster: 'Content', steps: [{ id: 's1', order: 1, name: 'Identify Series Angles', agent: 'Strategy', tool: 'Claude', outputKey: 'series_angles' }, { id: 's2', order: 2, name: 'Blog Outlines', agent: 'Copy', tool: 'Claude', outputKey: 'series_outlines' }, { id: 's3', order: 3, name: 'Draft Article 1', agent: 'Copy', tool: 'Claude', outputKey: 'article_1_draft', requiresApproval: true }] },
  { id: 'wf-010', slug: 'case-study-draft', name: 'Case Study Draft Generator', cluster: 'Content', steps: [{ id: 's1', order: 1, name: 'Structure Case Study', agent: 'Copy', tool: 'Claude', outputKey: 'case_study_structure' }, { id: 's2', order: 2, name: 'Full Case Study Draft', agent: 'Copy', tool: 'Claude', outputKey: 'case_study_draft' }, { id: 's3', order: 3, name: 'Short Summary Version', agent: 'Copy', tool: 'Claude', outputKey: 'case_study_summary', requiresApproval: true }] },
  { id: 'wf-011', slug: 'newsletter-digest', name: 'Newsletter Digest Generator', cluster: 'Content', steps: [{ id: 's1', order: 1, name: 'Summarize Articles', agent: 'Research', tool: 'Claude', outputKey: 'article_summaries' }, { id: 's2', order: 2, name: 'Write Newsletter', agent: 'Copy', tool: 'Claude', outputKey: 'newsletter_draft' }] },
  { id: 'wf-012', slug: 'executive-tone-rewriter', name: 'Executive Tone Rewriter', cluster: 'Content', steps: [{ id: 's1', order: 1, name: 'Tone Analysis', agent: 'Copy', tool: 'Claude', outputKey: 'tone_notes' }, { id: 's2', order: 2, name: 'Rewrites', agent: 'Copy', tool: 'Claude', outputKey: 'rewrites' }] },
  { id: 'wf-013', slug: 'linkedin-creative-generator', name: 'LinkedIn Creative Generator', cluster: 'Creative', steps: [{ id: 's1', order: 1, name: 'Creative Concepts', agent: 'Design', tool: 'Claude', outputKey: 'creative_concepts' }, { id: 's2', order: 2, name: 'Ad Copy Variants', agent: 'Copy', tool: 'Claude', outputKey: 'ad_copy' }, { id: 's3', order: 3, name: 'Canva Design Brief', agent: 'Design', tool: 'Canva', outputKey: 'design_brief', requiresApproval: true }] },
  { id: 'wf-014', slug: 'event-standee-generator', name: 'Event Standee Generator', cluster: 'Creative', steps: [{ id: 's1', order: 1, name: 'Standee Copy Options', agent: 'Copy', tool: 'Claude', outputKey: 'standee_copy' }, { id: 's2', order: 2, name: 'Design Direction Notes', agent: 'Design', tool: 'Claude', outputKey: 'design_notes' }] },
  { id: 'wf-015', slug: 'banner-ad-generator', name: 'Banner Ad Generator', cluster: 'Creative', steps: [{ id: 's1', order: 1, name: 'Copy Per Size', agent: 'Copy', tool: 'Claude', outputKey: 'banner_copy' }, { id: 's2', order: 2, name: 'Creative Prompts', agent: 'Design', tool: 'Claude', outputKey: 'creative_prompts' }] },
  { id: 'wf-016', slug: 'ebook-cover-generator', name: 'Ebook / Whitepaper Cover Generator', cluster: 'Creative', steps: [{ id: 's1', order: 1, name: 'Cover Concepts', agent: 'Design', tool: 'Claude', outputKey: 'cover_concepts' }, { id: 's2', order: 2, name: 'Canva Brief', agent: 'Design', tool: 'Canva', outputKey: 'canva_brief' }] },
  { id: 'wf-017', slug: 'event-promotion-kit', name: 'Event Promotion Kit', cluster: 'Event', steps: [{ id: 's1', order: 1, name: 'Invite Email', agent: 'Copy', tool: 'Claude', outputKey: 'invite_email' }, { id: 's2', order: 2, name: 'LinkedIn Post', agent: 'Copy', tool: 'Claude', outputKey: 'linkedin_post' }, { id: 's3', order: 3, name: 'Ad Copy', agent: 'Campaign', tool: 'LinkedIn Ads', outputKey: 'ad_copy' }] },
  { id: 'wf-018', slug: 'booth-messaging-pack', name: 'Booth Messaging Pack', cluster: 'Event', steps: [{ id: 's1', order: 1, name: 'Booth Messaging', agent: 'Copy', tool: 'Claude', outputKey: 'booth_messaging' }, { id: 's2', order: 2, name: 'Social Teaser', agent: 'Copy', tool: 'Claude', outputKey: 'social_teaser' }] },
  { id: 'wf-019', slug: 'event-account-outreach', name: 'Event Account Outreach Pack', cluster: 'Event', steps: [{ id: 's1', order: 1, name: 'Account Prioritization', agent: 'Research', tool: 'Claude', outputKey: 'account_priority' }, { id: 's2', order: 2, name: 'Personalized Invitations', agent: 'Copy', tool: 'Claude', outputKey: 'personalized_invites', requiresApproval: true }] },
  { id: 'wf-020', slug: 'post-event-followup', name: 'Post-Event Follow-Up Generator', cluster: 'Event', steps: [{ id: 's1', order: 1, name: 'Follow-Up Email Sequence', agent: 'Copy', tool: 'Claude', outputKey: 'followup_emails' }, { id: 's2', order: 2, name: 'LinkedIn Messages', agent: 'Copy', tool: 'Claude', outputKey: 'linkedin_messages' }, { id: 's3', order: 3, name: 'Event Recap Post', agent: 'Copy', tool: 'Claude', outputKey: 'recap_post' }] },
  { id: 'wf-021', slug: 'competitor-weekly-brief', name: 'Competitor Weekly Brief', cluster: 'Research', steps: [{ id: 's1', order: 1, name: 'Research Competitors', agent: 'Research', tool: 'Perplexity', outputKey: 'raw_research' }, { id: 's2', order: 2, name: 'Competitive Brief', agent: 'Competitor', tool: 'Claude', outputKey: 'competitive_brief' }] },
  { id: 'wf-022', slug: 'industry-trend-digest', name: 'Industry Trend Digest', cluster: 'Research', steps: [{ id: 's1', order: 1, name: 'Trend Research', agent: 'Research', tool: 'Perplexity', outputKey: 'trend_research' }, { id: 's2', order: 2, name: 'Trend Digest', agent: 'Research', tool: 'Claude', outputKey: 'trend_digest' }] },
  { id: 'wf-023', slug: 'messaging-gap-analysis', name: 'Messaging Gap Analysis', cluster: 'Research', steps: [{ id: 's1', order: 1, name: 'Messaging Analysis', agent: 'Competitor', tool: 'Claude', outputKey: 'messaging_analysis' }, { id: 's2', order: 2, name: 'Gap Analysis', agent: 'Strategy', tool: 'Claude', outputKey: 'gap_analysis' }] },
  { id: 'wf-024', slug: 'account-research-pack', name: 'Account Research Pack', cluster: 'Research', steps: [{ id: 's1', order: 1, name: 'Company Research', agent: 'Research', tool: 'Perplexity', outputKey: 'company_overview' }, { id: 's2', order: 2, name: 'Account Research Pack', agent: 'Research', tool: 'Claude', outputKey: 'account_pack' }] },
  { id: 'wf-025', slug: 'campaign-performance-summary', name: 'Campaign Performance Summary', cluster: 'Analytics', steps: [{ id: 's1', order: 1, name: 'Data Collection', agent: 'Analytics', tool: 'HubSpot', outputKey: 'raw_metrics' }, { id: 's2', order: 2, name: 'Performance Summary', agent: 'Analytics', tool: 'Claude', outputKey: 'performance_summary' }, { id: 's3', order: 3, name: 'Recommendations', agent: 'Analytics', tool: 'Claude', outputKey: 'recommendations' }] },
  { id: 'wf-026', slug: 'funnel-dropoff-diagnosis', name: 'Funnel Drop-Off Diagnosis', cluster: 'Analytics', steps: [{ id: 's1', order: 1, name: 'Drop-Off Analysis', agent: 'Analytics', tool: 'Claude', outputKey: 'dropoff_analysis' }, { id: 's2', order: 2, name: 'Root Cause & Recommendations', agent: 'Analytics', tool: 'Claude', outputKey: 'optimization_ideas' }] },
  { id: 'wf-027', slug: 'channel-performance-comparison', name: 'Channel Performance Comparison', cluster: 'Analytics', steps: [{ id: 's1', order: 1, name: 'Channel Analysis', agent: 'Analytics', tool: 'Claude', outputKey: 'channel_comparison' }, { id: 's2', order: 2, name: 'Budget Recommendations', agent: 'Analytics', tool: 'Claude', outputKey: 'budget_recommendations' }] },
  { id: 'wf-028', slug: 'one-pager-generator', name: 'One-Pager Generator', cluster: 'Sales', steps: [{ id: 's1', order: 1, name: 'Messaging Framework', agent: 'Strategy', tool: 'Claude', outputKey: 'messaging' }, { id: 's2', order: 2, name: 'One-Pager Copy', agent: 'Copy', tool: 'Claude', outputKey: 'one_pager_copy', requiresApproval: true }] },
  { id: 'wf-029', slug: 'battlecard-generator', name: 'Battlecard Generator', cluster: 'Sales', steps: [{ id: 's1', order: 1, name: 'Competitor Research', agent: 'Research', tool: 'Perplexity', outputKey: 'competitor_research' }, { id: 's2', order: 2, name: 'Battlecard', agent: 'Strategy', tool: 'Claude', outputKey: 'battlecard' }] },
  { id: 'wf-030', slug: 'meeting-brief-generator', name: 'Meeting Brief Generator', cluster: 'Sales', steps: [{ id: 's1', order: 1, name: 'Company & Stakeholder Research', agent: 'Research', tool: 'Perplexity', outputKey: 'company_research' }, { id: 's2', order: 2, name: 'Meeting Brief', agent: 'Research', tool: 'Claude', outputKey: 'meeting_brief' }] },
];

export function getWorkflowRef(idOrSlug: string): WorkflowRef | undefined {
  return MARKETING_WORKFLOW_REFS.find((w) => w.id === idOrSlug || w.slug === idOrSlug);
}
