/**
 * Marketing Workflows — Gateway copy for API execution
 * Mirrors apps/web marketing-workflows.ts structure for execution.
 * Uses UnifiedSkillDef from @agentos/skills for cross-persona consistency.
 * Marketing items are typed as 'workflow' (multi-step composed templates).
 * @author Phani Marupaka <https://linkedin.com/in/phani-marupaka>
 * @copyright © 2026 Phani Marupaka. All rights reserved.
 */

import type { UnifiedSkillDef, UnifiedStepDef } from '../../../packages/skills/src/schema.js';

// Re-export for backward compat
export type WorkflowStepRef = UnifiedStepDef;
export type WorkflowRef = UnifiedSkillDef;

// Minimal workflow refs for execution — full definitions live in apps/web
export const MARKETING_WORKFLOW_REFS: UnifiedSkillDef[] = [
  { id: 'wf-001', slug: 'webinar-campaign-generator', name: 'Webinar Campaign Generator', description: 'End-to-end webinar campaign: strategy, emails, ads, landing page, and follow-up.', icon: '🎙️', persona: 'marketing', executableType: 'workflow', cluster: 'Campaign', complexity: 'complex', estimatedTime: '3–5 min', inputs: [], outputs: ['strategy', 'email_series', 'linkedin_ads', 'landing_page', 'followup_emails'], requiredTools: ['Claude'], optionalTools: ['LinkedIn Ads'], tags: ['webinar', 'campaign', 'multi-channel'], steps: [{ id: 's1', order: 1, name: 'Audience & Messaging Strategy', agent: 'Strategy', tool: 'Claude', outputKey: 'strategy' }, { id: 's2', order: 2, name: 'Write Invite Email Series', agent: 'Copy', tool: 'Claude', outputKey: 'email_series' }, { id: 's3', order: 3, name: 'LinkedIn Ad Copy', agent: 'Campaign', tool: 'LinkedIn Ads', outputKey: 'linkedin_ads' }, { id: 's4', order: 4, name: 'Landing Page Copy', agent: 'Copy', tool: 'Claude', outputKey: 'landing_page' }, { id: 's5', order: 5, name: 'Post-Webinar Follow-Up', agent: 'Copy', tool: 'Claude', outputKey: 'followup_emails', requiresApproval: true }] },
  { id: 'wf-002', slug: 'product-launch-campaign', name: 'Product Launch Campaign Builder', description: 'Product Launch Campaign Builder workflow.', icon: '📢', persona: 'marketing', executableType: 'workflow', cluster: 'Campaign', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['messaging', 'email_series', 'landing_page', 'linkedin_posts'], requiredTools: ['Claude'], optionalTools: [], tags: ['campaign', 'multi-step'], steps: [{ id: 's1', order: 1, name: 'Launch Messaging Framework', agent: 'Strategy', tool: 'Claude', outputKey: 'messaging' }, { id: 's2', order: 2, name: 'Email Launch Series', agent: 'Copy', tool: 'Claude', outputKey: 'email_series' }, { id: 's3', order: 3, name: 'Landing Page Copy', agent: 'Copy', tool: 'Claude', outputKey: 'landing_page', requiresApproval: true }, { id: 's4', order: 4, name: 'LinkedIn Post Series', agent: 'Copy', tool: 'Claude', outputKey: 'linkedin_posts' }] },
  { id: 'wf-003', slug: 'abm-outreach-campaign', name: 'ABM Outreach Campaign', description: 'ABM Outreach Campaign workflow.', icon: '📢', persona: 'marketing', executableType: 'workflow', cluster: 'Campaign', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['account_segments', 'personalized_messaging', 'outreach_emails', 'linkedin_messages'], requiredTools: ['Claude'], optionalTools: [], tags: ['campaign', 'multi-step'], steps: [{ id: 's1', order: 1, name: 'Account Segmentation', agent: 'Research', tool: 'Perplexity', outputKey: 'account_segments' }, { id: 's2', order: 2, name: 'Personalized Messaging', agent: 'Strategy', tool: 'Claude', outputKey: 'personalized_messaging' }, { id: 's3', order: 3, name: 'Outreach Email Templates', agent: 'Copy', tool: 'Claude', outputKey: 'outreach_emails' }, { id: 's4', order: 4, name: 'LinkedIn Message Templates', agent: 'Copy', tool: 'Claude', outputKey: 'linkedin_messages', requiresApproval: true }] },
  { id: 'wf-004', slug: 'paid-media-campaign-pack', name: 'Paid Media Campaign Pack', description: 'Paid Media Campaign Pack workflow.', icon: '📢', persona: 'marketing', executableType: 'workflow', cluster: 'Campaign', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['campaign_brief', 'ad_copy', 'creative_prompts'], requiredTools: ['Claude'], optionalTools: [], tags: ['campaign', 'multi-step'], steps: [{ id: 's1', order: 1, name: 'Campaign Strategy', agent: 'Strategy', tool: 'Claude', outputKey: 'campaign_brief' }, { id: 's2', order: 2, name: 'Ad Copy Variants', agent: 'Copy', tool: 'Claude', outputKey: 'ad_copy' }, { id: 's3', order: 3, name: 'Creative Prompts', agent: 'Copy', tool: 'Claude', outputKey: 'creative_prompts' }] },
  { id: 'wf-005', slug: 'multi-channel-campaign-planner', name: 'Multi-Channel Campaign Planner', description: 'Multi-Channel Campaign Planner workflow.', icon: '📢', persona: 'marketing', executableType: 'workflow', cluster: 'Campaign', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['messaging_matrix', 'channel_plan', 'creative_checklist'], requiredTools: ['Claude'], optionalTools: [], tags: ['campaign', 'multi-step'], steps: [{ id: 's1', order: 1, name: 'Messaging Matrix', agent: 'Strategy', tool: 'Claude', outputKey: 'messaging_matrix' }, { id: 's2', order: 2, name: 'Channel Plan', agent: 'Campaign', tool: 'Claude', outputKey: 'channel_plan' }, { id: 's3', order: 3, name: 'Creative Checklist', agent: 'Campaign', tool: 'Claude', outputKey: 'creative_checklist' }] },
  { id: 'wf-006', slug: 'nurture-email-sequence', name: 'Nurture Email Sequence Builder', description: 'Nurture Email Sequence Builder workflow.', icon: '📢', persona: 'marketing', executableType: 'workflow', cluster: 'Campaign', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['sequence_strategy', 'email_sequence', 'subject_variants'], requiredTools: ['Claude'], optionalTools: [], tags: ['campaign', 'multi-step'], steps: [{ id: 's1', order: 1, name: 'Sequence Strategy', agent: 'Strategy', tool: 'Claude', outputKey: 'sequence_strategy' }, { id: 's2', order: 2, name: 'Email Drafts', agent: 'Copy', tool: 'Claude', outputKey: 'email_sequence' }, { id: 's3', order: 3, name: 'Subject Line Variants', agent: 'Copy', tool: 'Claude', outputKey: 'subject_variants', requiresApproval: true }] },
  { id: 'wf-007', slug: 'blog-from-brief', name: 'Blog From Brief', description: 'Blog From Brief workflow.', icon: '✍️', persona: 'marketing', executableType: 'workflow', cluster: 'Content', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['outline', 'blog_draft', 'seo_metadata'], requiredTools: ['Claude'], optionalTools: [], tags: ['content', 'writing'], steps: [{ id: 's1', order: 1, name: 'Outline & Structure', agent: 'Copy', tool: 'Claude', outputKey: 'outline' }, { id: 's2', order: 2, name: 'Blog Draft', agent: 'Copy', tool: 'Claude', outputKey: 'blog_draft' }, { id: 's3', order: 3, name: 'SEO Metadata', agent: 'Copy', tool: 'Claude', outputKey: 'seo_metadata' }] },
  { id: 'wf-008', slug: 'blog-from-whitepaper', name: 'Blog From Whitepaper', description: 'Blog From Whitepaper workflow.', icon: '✍️', persona: 'marketing', executableType: 'workflow', cluster: 'Content', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['key_insights', 'outline', 'blog_draft'], requiredTools: ['Claude'], optionalTools: [], tags: ['content', 'writing'], steps: [{ id: 's1', order: 1, name: 'Extract Key Insights', agent: 'Research', tool: 'Claude', outputKey: 'key_insights' }, { id: 's2', order: 2, name: 'Blog Outline', agent: 'Copy', tool: 'Claude', outputKey: 'outline' }, { id: 's3', order: 3, name: 'Blog Draft', agent: 'Copy', tool: 'Claude', outputKey: 'blog_draft', requiresApproval: true }] },
  { id: 'wf-009', slug: 'blog-series-generator', name: 'Blog Series Generator', description: 'Blog Series Generator workflow.', icon: '✍️', persona: 'marketing', executableType: 'workflow', cluster: 'Content', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['series_angles', 'series_outlines', 'article_1_draft'], requiredTools: ['Claude'], optionalTools: [], tags: ['content', 'writing'], steps: [{ id: 's1', order: 1, name: 'Identify Series Angles', agent: 'Strategy', tool: 'Claude', outputKey: 'series_angles' }, { id: 's2', order: 2, name: 'Blog Outlines', agent: 'Copy', tool: 'Claude', outputKey: 'series_outlines' }, { id: 's3', order: 3, name: 'Draft Article 1', agent: 'Copy', tool: 'Claude', outputKey: 'article_1_draft', requiresApproval: true }] },
  { id: 'wf-010', slug: 'case-study-draft', name: 'Case Study Draft Generator', description: 'Case Study Draft Generator workflow.', icon: '✍️', persona: 'marketing', executableType: 'workflow', cluster: 'Content', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['case_study_structure', 'case_study_draft', 'case_study_summary'], requiredTools: ['Claude'], optionalTools: [], tags: ['content', 'writing'], steps: [{ id: 's1', order: 1, name: 'Structure Case Study', agent: 'Copy', tool: 'Claude', outputKey: 'case_study_structure' }, { id: 's2', order: 2, name: 'Full Case Study Draft', agent: 'Copy', tool: 'Claude', outputKey: 'case_study_draft' }, { id: 's3', order: 3, name: 'Short Summary Version', agent: 'Copy', tool: 'Claude', outputKey: 'case_study_summary', requiresApproval: true }] },
  { id: 'wf-011', slug: 'newsletter-digest', name: 'Newsletter Digest Generator', description: 'Newsletter Digest Generator workflow.', icon: '✍️', persona: 'marketing', executableType: 'workflow', cluster: 'Content', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['article_summaries', 'newsletter_draft'], requiredTools: ['Claude'], optionalTools: [], tags: ['content', 'writing'], steps: [{ id: 's1', order: 1, name: 'Summarize Articles', agent: 'Research', tool: 'Claude', outputKey: 'article_summaries' }, { id: 's2', order: 2, name: 'Write Newsletter', agent: 'Copy', tool: 'Claude', outputKey: 'newsletter_draft' }] },
  { id: 'wf-012', slug: 'executive-tone-rewriter', name: 'Executive Tone Rewriter', description: 'Executive Tone Rewriter workflow.', icon: '✍️', persona: 'marketing', executableType: 'workflow', cluster: 'Content', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['tone_notes', 'rewrites'], requiredTools: ['Claude'], optionalTools: [], tags: ['content', 'writing'], steps: [{ id: 's1', order: 1, name: 'Tone Analysis', agent: 'Copy', tool: 'Claude', outputKey: 'tone_notes' }, { id: 's2', order: 2, name: 'Rewrites', agent: 'Copy', tool: 'Claude', outputKey: 'rewrites' }] },
  { id: 'wf-013', slug: 'linkedin-creative-generator', name: 'LinkedIn Creative Generator', description: 'LinkedIn Creative Generator workflow.', icon: '🎨', persona: 'marketing', executableType: 'workflow', cluster: 'Creative', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['creative_concepts', 'ad_copy', 'design_brief'], requiredTools: ['Claude'], optionalTools: [], tags: ['creative', 'design'], steps: [{ id: 's1', order: 1, name: 'Creative Concepts', agent: 'Design', tool: 'Claude', outputKey: 'creative_concepts' }, { id: 's2', order: 2, name: 'Ad Copy Variants', agent: 'Copy', tool: 'Claude', outputKey: 'ad_copy' }, { id: 's3', order: 3, name: 'Canva Design Brief', agent: 'Design', tool: 'Canva', outputKey: 'design_brief', requiresApproval: true }] },
  { id: 'wf-014', slug: 'event-standee-generator', name: 'Event Standee Generator', description: 'Event Standee Generator workflow.', icon: '🎨', persona: 'marketing', executableType: 'workflow', cluster: 'Creative', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['standee_copy', 'design_notes'], requiredTools: ['Claude'], optionalTools: [], tags: ['creative', 'design'], steps: [{ id: 's1', order: 1, name: 'Standee Copy Options', agent: 'Copy', tool: 'Claude', outputKey: 'standee_copy' }, { id: 's2', order: 2, name: 'Design Direction Notes', agent: 'Design', tool: 'Claude', outputKey: 'design_notes' }] },
  { id: 'wf-015', slug: 'banner-ad-generator', name: 'Banner Ad Generator', description: 'Banner Ad Generator workflow.', icon: '🎨', persona: 'marketing', executableType: 'workflow', cluster: 'Creative', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['banner_copy', 'creative_prompts'], requiredTools: ['Claude'], optionalTools: [], tags: ['creative', 'design'], steps: [{ id: 's1', order: 1, name: 'Copy Per Size', agent: 'Copy', tool: 'Claude', outputKey: 'banner_copy' }, { id: 's2', order: 2, name: 'Creative Prompts', agent: 'Design', tool: 'Claude', outputKey: 'creative_prompts' }] },
  { id: 'wf-016', slug: 'ebook-cover-generator', name: 'Ebook / Whitepaper Cover Generator', description: 'Ebook / Whitepaper Cover Generator workflow.', icon: '🎨', persona: 'marketing', executableType: 'workflow', cluster: 'Creative', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['cover_concepts', 'canva_brief'], requiredTools: ['Claude'], optionalTools: [], tags: ['creative', 'design'], steps: [{ id: 's1', order: 1, name: 'Cover Concepts', agent: 'Design', tool: 'Claude', outputKey: 'cover_concepts' }, { id: 's2', order: 2, name: 'Canva Brief', agent: 'Design', tool: 'Canva', outputKey: 'canva_brief' }] },
  { id: 'wf-017', slug: 'event-promotion-kit', name: 'Event Promotion Kit', description: 'Event Promotion Kit workflow.', icon: '🎪', persona: 'marketing', executableType: 'workflow', cluster: 'Event', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['invite_email', 'linkedin_post', 'ad_copy'], requiredTools: ['Claude'], optionalTools: [], tags: ['event', 'marketing'], steps: [{ id: 's1', order: 1, name: 'Invite Email', agent: 'Copy', tool: 'Claude', outputKey: 'invite_email' }, { id: 's2', order: 2, name: 'LinkedIn Post', agent: 'Copy', tool: 'Claude', outputKey: 'linkedin_post' }, { id: 's3', order: 3, name: 'Ad Copy', agent: 'Campaign', tool: 'LinkedIn Ads', outputKey: 'ad_copy' }] },
  { id: 'wf-018', slug: 'booth-messaging-pack', name: 'Booth Messaging Pack', description: 'Booth Messaging Pack workflow.', icon: '🎪', persona: 'marketing', executableType: 'workflow', cluster: 'Event', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['booth_messaging', 'social_teaser'], requiredTools: ['Claude'], optionalTools: [], tags: ['event', 'marketing'], steps: [{ id: 's1', order: 1, name: 'Booth Messaging', agent: 'Copy', tool: 'Claude', outputKey: 'booth_messaging' }, { id: 's2', order: 2, name: 'Social Teaser', agent: 'Copy', tool: 'Claude', outputKey: 'social_teaser' }] },
  { id: 'wf-019', slug: 'event-account-outreach', name: 'Event Account Outreach Pack', description: 'Event Account Outreach Pack workflow.', icon: '🎪', persona: 'marketing', executableType: 'workflow', cluster: 'Event', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['account_priority', 'personalized_invites'], requiredTools: ['Claude'], optionalTools: [], tags: ['event', 'marketing'], steps: [{ id: 's1', order: 1, name: 'Account Prioritization', agent: 'Research', tool: 'Claude', outputKey: 'account_priority' }, { id: 's2', order: 2, name: 'Personalized Invitations', agent: 'Copy', tool: 'Claude', outputKey: 'personalized_invites', requiresApproval: true }] },
  { id: 'wf-020', slug: 'post-event-followup', name: 'Post-Event Follow-Up Generator', description: 'Post-Event Follow-Up Generator workflow.', icon: '🎪', persona: 'marketing', executableType: 'workflow', cluster: 'Event', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['followup_emails', 'linkedin_messages', 'recap_post'], requiredTools: ['Claude'], optionalTools: [], tags: ['event', 'marketing'], steps: [{ id: 's1', order: 1, name: 'Follow-Up Email Sequence', agent: 'Copy', tool: 'Claude', outputKey: 'followup_emails' }, { id: 's2', order: 2, name: 'LinkedIn Messages', agent: 'Copy', tool: 'Claude', outputKey: 'linkedin_messages' }, { id: 's3', order: 3, name: 'Event Recap Post', agent: 'Copy', tool: 'Claude', outputKey: 'recap_post' }] },
  { id: 'wf-021', slug: 'competitor-weekly-brief', name: 'Competitor Weekly Brief', description: 'Competitor Weekly Brief workflow.', icon: '🔬', persona: 'marketing', executableType: 'workflow', cluster: 'Research', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['raw_research', 'competitive_brief'], requiredTools: ['Claude'], optionalTools: [], tags: ['research', 'analysis'], steps: [{ id: 's1', order: 1, name: 'Research Competitors', agent: 'Research', tool: 'Perplexity', outputKey: 'raw_research' }, { id: 's2', order: 2, name: 'Competitive Brief', agent: 'Competitor', tool: 'Claude', outputKey: 'competitive_brief' }] },
  { id: 'wf-022', slug: 'industry-trend-digest', name: 'Industry Trend Digest', description: 'Industry Trend Digest workflow.', icon: '🔬', persona: 'marketing', executableType: 'workflow', cluster: 'Research', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['trend_research', 'trend_digest'], requiredTools: ['Claude'], optionalTools: [], tags: ['research', 'analysis'], steps: [{ id: 's1', order: 1, name: 'Trend Research', agent: 'Research', tool: 'Perplexity', outputKey: 'trend_research' }, { id: 's2', order: 2, name: 'Trend Digest', agent: 'Research', tool: 'Claude', outputKey: 'trend_digest' }] },
  { id: 'wf-023', slug: 'messaging-gap-analysis', name: 'Messaging Gap Analysis', description: 'Messaging Gap Analysis workflow.', icon: '🔬', persona: 'marketing', executableType: 'workflow', cluster: 'Research', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['messaging_analysis', 'gap_analysis'], requiredTools: ['Claude'], optionalTools: [], tags: ['research', 'analysis'], steps: [{ id: 's1', order: 1, name: 'Messaging Analysis', agent: 'Competitor', tool: 'Claude', outputKey: 'messaging_analysis' }, { id: 's2', order: 2, name: 'Gap Analysis', agent: 'Strategy', tool: 'Claude', outputKey: 'gap_analysis' }] },
  { id: 'wf-024', slug: 'account-research-pack', name: 'Account Research Pack', description: 'Account Research Pack workflow.', icon: '🔬', persona: 'marketing', executableType: 'workflow', cluster: 'Research', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['company_overview', 'account_pack'], requiredTools: ['Claude'], optionalTools: [], tags: ['research', 'analysis'], steps: [{ id: 's1', order: 1, name: 'Company Research', agent: 'Research', tool: 'Perplexity', outputKey: 'company_overview' }, { id: 's2', order: 2, name: 'Account Research Pack', agent: 'Research', tool: 'Claude', outputKey: 'account_pack' }] },
  { id: 'wf-025', slug: 'campaign-performance-summary', name: 'Campaign Performance Summary', description: 'Campaign Performance Summary workflow.', icon: '📊', persona: 'marketing', executableType: 'workflow', cluster: 'Analytics', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['raw_metrics', 'performance_summary', 'recommendations'], requiredTools: ['Claude'], optionalTools: [], tags: ['analytics', 'reporting'], steps: [{ id: 's1', order: 1, name: 'Data Collection', agent: 'Analytics', tool: 'HubSpot', outputKey: 'raw_metrics' }, { id: 's2', order: 2, name: 'Performance Summary', agent: 'Analytics', tool: 'Claude', outputKey: 'performance_summary' }, { id: 's3', order: 3, name: 'Recommendations', agent: 'Analytics', tool: 'Claude', outputKey: 'recommendations' }] },
  { id: 'wf-026', slug: 'funnel-dropoff-diagnosis', name: 'Funnel Drop-Off Diagnosis', description: 'Funnel Drop-Off Diagnosis workflow.', icon: '📊', persona: 'marketing', executableType: 'workflow', cluster: 'Analytics', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['dropoff_analysis', 'optimization_ideas'], requiredTools: ['Claude'], optionalTools: [], tags: ['analytics', 'reporting'], steps: [{ id: 's1', order: 1, name: 'Drop-Off Analysis', agent: 'Analytics', tool: 'Claude', outputKey: 'dropoff_analysis' }, { id: 's2', order: 2, name: 'Root Cause & Recommendations', agent: 'Analytics', tool: 'Claude', outputKey: 'optimization_ideas' }] },
  { id: 'wf-027', slug: 'channel-performance-comparison', name: 'Channel Performance Comparison', description: 'Channel Performance Comparison workflow.', icon: '📊', persona: 'marketing', executableType: 'workflow', cluster: 'Analytics', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['channel_comparison', 'budget_recommendations'], requiredTools: ['Claude'], optionalTools: [], tags: ['analytics', 'reporting'], steps: [{ id: 's1', order: 1, name: 'Channel Analysis', agent: 'Analytics', tool: 'Claude', outputKey: 'channel_comparison' }, { id: 's2', order: 2, name: 'Budget Recommendations', agent: 'Analytics', tool: 'Claude', outputKey: 'budget_recommendations' }] },
  { id: 'wf-028', slug: 'one-pager-generator', name: 'One-Pager Generator', description: 'One-Pager Generator workflow.', icon: '💼', persona: 'marketing', executableType: 'workflow', cluster: 'Sales', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['messaging', 'one_pager_copy'], requiredTools: ['Claude'], optionalTools: [], tags: ['sales', 'enablement'], steps: [{ id: 's1', order: 1, name: 'Messaging Framework', agent: 'Strategy', tool: 'Claude', outputKey: 'messaging' }, { id: 's2', order: 2, name: 'One-Pager Copy', agent: 'Copy', tool: 'Claude', outputKey: 'one_pager_copy', requiresApproval: true }] },
  { id: 'wf-029', slug: 'battlecard-generator', name: 'Battlecard Generator', description: 'Battlecard Generator workflow.', icon: '💼', persona: 'marketing', executableType: 'workflow', cluster: 'Sales', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['competitor_research', 'battlecard'], requiredTools: ['Claude'], optionalTools: [], tags: ['sales', 'enablement'], steps: [{ id: 's1', order: 1, name: 'Competitor Research', agent: 'Research', tool: 'Perplexity', outputKey: 'competitor_research' }, { id: 's2', order: 2, name: 'Battlecard', agent: 'Strategy', tool: 'Claude', outputKey: 'battlecard' }] },
  { id: 'wf-030', slug: 'meeting-brief-generator', name: 'Meeting Brief Generator', description: 'Meeting Brief Generator workflow.', icon: '💼', persona: 'marketing', executableType: 'workflow', cluster: 'Sales', complexity: 'moderate', estimatedTime: '2-4 min', inputs: [], outputs: ['company_research', 'meeting_brief'], requiredTools: ['Claude'], optionalTools: [], tags: ['sales', 'enablement'], steps: [{ id: 's1', order: 1, name: 'Company & Stakeholder Research', agent: 'Research', tool: 'Perplexity', outputKey: 'company_research' }, { id: 's2', order: 2, name: 'Meeting Brief', agent: 'Research', tool: 'Claude', outputKey: 'meeting_brief' }] },
];

export function getWorkflowRef(idOrSlug: string): WorkflowRef | undefined {
  return MARKETING_WORKFLOW_REFS.find((w) => w.id === idOrSlug || w.slug === idOrSlug);
}
