/**
 * Persona API — Shared execution runtime for Engineering and Product personas
 * Uses the same Claude-backed step execution pattern as Marketing workflows.
 * @author Phani Marupaka <https://linkedin.com/in/phani-marupaka>
 * @copyright © 2026 Phani Marupaka. All rights reserved.
 */

import type { PersonaSkillDef, SkillStep } from './engineering-skills-data.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface PersonaExecutionRecord {
  id: string;
  persona: 'engineering' | 'product';
  skillId: string;
  skillName: string;
  status: 'queued' | 'running' | 'completed' | 'failed';
  steps: Array<{
    stepId: string;
    stepName: string;
    agent: string;
    tool?: string;
    status: string;
    startedAt?: string;
    completedAt?: string;
    outputKey?: string;
    outputPreview?: string;
    error?: string;
  }>;
  outputs: Record<string, string>;
  inputs: Record<string, unknown>;
  startedAt: string;
  completedAt?: string;
  userId?: string;
}

// ---------------------------------------------------------------------------
// In-memory execution store
// ---------------------------------------------------------------------------

const executions = new Map<string, PersonaExecutionRecord>();

// ---------------------------------------------------------------------------
// Claude API call
// ---------------------------------------------------------------------------

async function callClaude(systemPrompt: string, userPrompt: string): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY;

  if (!apiKey) {
    return generatePlaceholder(userPrompt);
  }

  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-6-20251001',
      max_tokens: 4096,
      system: systemPrompt,
      messages: [{ role: 'user', content: userPrompt }],
    }),
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Claude API error ${res.status}: ${errText}`);
  }

  const data = (await res.json()) as { content: Array<{ text: string }> };
  return data.content?.[0]?.text ?? '';
}

function generatePlaceholder(prompt: string): string {
  const topic = prompt.slice(0, 120).trim();
  return `# AI-Generated Output\n\n*Configure ANTHROPIC_API_KEY to enable real Claude generation.*\n\n**Task:** ${topic}\n\nThis section would contain AI-generated content specific to your inputs.\n\n*Generated by AgentOS Persona Engine*`;
}

// ---------------------------------------------------------------------------
// Prompt builder
// ---------------------------------------------------------------------------

function buildStepPrompt(
  persona: 'engineering' | 'product',
  skillName: string,
  step: SkillStep,
  inputs: Record<string, unknown>,
  previousOutputs: Record<string, string>
): { system: string; user: string } {
  const inputLines = Object.entries(inputs)
    .filter(([k, v]) => v !== undefined && v !== '' && v !== null)
    .map(([k, v]) => {
      const label = k.replace(/_/g, ' ');
      const val = Array.isArray(v) ? v.join(', ') : String(v);
      return `**${label}**: ${val}`;
    })
    .join('\n');

  const prevContext =
    Object.keys(previousOutputs).length > 0
      ? '\n\n## Context from Previous Steps\n\n' +
        Object.entries(previousOutputs)
          .map(([k, v]) => `### ${k.replace(/_/g, ' ')}\n${v.slice(0, 800)}${v.length > 800 ? '\n...[truncated]' : ''}`)
          .join('\n\n')
      : '';

  const personaDescription =
    persona === 'engineering'
      ? 'expert software engineer and technical lead helping engineering teams with code quality, testing, CI/CD, architecture, documentation, and incident response'
      : 'expert product manager and strategist helping product teams with requirements, planning, roadmaps, stakeholder communication, and customer research';

  const system = `You are an ${personaDescription} working inside AgentOS, an AI operating system.

You are executing the "${skillName}" skill. Produce high-quality, specific, immediately usable output.

Guidelines:
- Be concrete and specific — no generic filler
- Format output with clear sections, headers, and bullet points where appropriate
- Write in a professional, technical tone appropriate for your audience
- Output should be ready to review and use with minimal editing
- Include actionable recommendations and specific details`;

  const user = `## Skill Step: ${step.name}

## User Inputs
${inputLines || 'No structured inputs provided.'}${prevContext}

Please execute this step now. Produce specific, high-quality output for: "${step.name}".`;

  return { system, user };
}

// ---------------------------------------------------------------------------
// Execution Runtime
// ---------------------------------------------------------------------------

async function processSkillSteps(
  execId: string,
  persona: 'engineering' | 'product',
  skill: PersonaSkillDef,
  inputs: Record<string, unknown>,
  simulate: boolean
): Promise<void> {
  const exec = executions.get(execId);
  if (!exec) return;

  exec.status = 'running';
  executions.set(execId, exec);

  const previousOutputs: Record<string, string> = {};

  for (let i = 0; i < skill.steps.length; i++) {
    const skillStep = skill.steps[i];
    const stepRecord = exec.steps[i];

    if (!skillStep || !stepRecord) continue;

    // Mark step as running
    stepRecord.status = 'running';
    stepRecord.startedAt = new Date().toISOString();
    executions.set(execId, exec);

    try {
      let output: string;

      if (simulate) {
        await new Promise((r) => setTimeout(r, 400 + Math.random() * 600));
        output = `[Simulation] ${skillStep.name} completed successfully.\n\nThis is a simulated output for the "${skillStep.name}" step of the "${skill.name}" skill. Configure real tool connections and disable simulation to generate actual content.`;
      } else {
        const { system, user } = buildStepPrompt(persona, skill.name, skillStep, inputs, previousOutputs);
        output = await callClaude(system, user);
      }

      previousOutputs[skillStep.outputKey] = output;
      exec.outputs[skillStep.outputKey] = output;

      stepRecord.status = skillStep.requiresApproval ? 'approval_required' : 'completed';
      stepRecord.completedAt = new Date().toISOString();
      stepRecord.outputKey = skillStep.outputKey;
      stepRecord.outputPreview = output.slice(0, 300);

      // Pause and wait for approval if required (in real system, would suspend)
      if (skillStep.requiresApproval && !simulate) {
        // Continue automatically in this runtime — approval UI is informational
      }
    } catch (err) {
      stepRecord.status = 'failed';
      stepRecord.completedAt = new Date().toISOString();
      stepRecord.error = err instanceof Error ? err.message : 'Step failed';
      console.error(`[persona-api] Step ${skillStep.id} failed:`, err);
      // Continue to next step (partial execution)
    }

    executions.set(execId, exec);
  }

  const anyFailed = exec.steps.some((s) => s.status === 'failed');
  exec.status = anyFailed ? 'failed' : 'completed';
  exec.completedAt = new Date().toISOString();
  executions.set(execId, exec);
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function createPersonaExecution(
  persona: 'engineering' | 'product',
  skill: PersonaSkillDef,
  inputs: Record<string, unknown>,
  userId?: string,
  simulate?: boolean
): PersonaExecutionRecord {
  const id = `${persona}-exec-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;

  const steps = skill.steps.map((s) => ({
    stepId: s.id,
    stepName: s.name,
    agent: s.agent,
    tool: s.tool,
    status: 'pending' as const,
    outputKey: s.outputKey,
  }));

  const exec: PersonaExecutionRecord = {
    id,
    persona,
    skillId: skill.id,
    skillName: skill.name,
    status: 'queued',
    steps,
    outputs: {},
    inputs,
    startedAt: new Date().toISOString(),
    userId,
  };

  executions.set(id, exec);

  // Fire execution asynchronously
  processSkillSteps(id, persona, skill, inputs, simulate ?? false).catch((err) => {
    console.error(`[persona-api] processSkillSteps error for ${id}:`, err);
    const e = executions.get(id);
    if (e) { e.status = 'failed'; executions.set(id, e); }
  });

  return exec;
}

export function getPersonaExecution(execId: string): PersonaExecutionRecord | undefined {
  return executions.get(execId);
}

export function listPersonaExecutions(persona: 'engineering' | 'product', limit = 20): PersonaExecutionRecord[] {
  const all = Array.from(executions.values())
    .filter((e) => e.persona === persona)
    .sort((a, b) => new Date(b.startedAt).getTime() - new Date(a.startedAt).getTime())
    .slice(0, limit);
  return all;
}

export function approvePersonaStep(execId: string, stepId: string): { success: boolean; message: string } {
  const exec = executions.get(execId);
  if (!exec) return { success: false, message: 'Execution not found' };
  const step = exec.steps.find((s) => s.stepId === stepId);
  if (!step) return { success: false, message: 'Step not found' };
  if (step.status !== 'approval_required') return { success: false, message: 'Step is not awaiting approval' };
  step.status = 'completed';
  executions.set(execId, exec);
  return { success: true, message: 'Step approved' };
}
