{{- define "common.probe" }}
{{- if (.Values.probe).enabled }}
{{- range .Values.probe.targets }}
{{- if .enabled }}
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: {{ template "common.fullname" $ }}-{{ .name }}-probe
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.olympus-labels" $.Values | nindent 4 }}
    {{- range $key, $value := .labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  module: "{{default "http_2xx" .module }}"
  jobName: "{{ template "common.fullname" $ }}-{{ .name }}-probe"
  interval: {{ default "60s" .interval }}
  scrapeTimeout: {{ default "10s" .scrapeTimeout }}
  prober:
    url: olympus-zone-monitoring-prometheus-blackbox-exporter.zone-monitoring.svc.cluster.local.:9115
  targets:
    staticConfig:
      labels:
        target: "{{ .name }}"
        module: "{{ default "http_2xx" .module }}"
	      {{- range $key, $value := .mertriclabels }}
        {{ $key }}: {{ $value | quote }}
	      {{- end }}
      static:
      {{- range .urls }}
      - {{ . | quote }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}