{{- define "common.http-health-check-servicemonitor" }}
{{- if (.Values.httpHealthCheckServiceMonitor).enabled }}
{{- range .Values.httpHealthCheckServiceMonitor.targets }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "common.fullname" $ }}-http-health-servicemonitor-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.olympus-labels" $.Values | nindent 4 }}
    {{- range $key, $value := .labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  endpoints:
  - port: http
    scheme: http
    path: "/probe"
    interval: {{ default "120s" .interval }}
    scrapeTimeout: {{ default "5s" .scrapeTimeout }}
    params:
      module:
      - {{ default "http_2xx" .module }}
      target:
      - {{ .url }}
    metricRelabelings:
      - sourceLabels: [__address__]
        targetLabel: __param_target
      - sourceLabels: [__param_target]
        targetLabel: instance
      - targetLabel: target
        replacement: {{ .name }}
  jobLabel: "{{ $.Release.Name }}"
  selector:
    matchLabels:
      app.kubernetes.io/instance: olympus-zone-monitoring
      app.kubernetes.io/name: prometheus-blackbox-exporter
  namespaceSelector:
    matchNames:
      - zone-monitoring
{{- end }}
{{- end }}
{{- end }}