{{- if .Values.HeraclesClusterRoute.enabled }}
{{- range .Values.HeraclesClusterRoute.routes }}
{{- $svcPort := default 80 .service.port }}
apiVersion: zeta.tech/v1alpha1
kind: HeraclesClusterRoute
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  paths:
    {{- range .paths }}
    - {{ . | quote }}
    {{- end }}
  backend:
    port: {{ $svcPort }}
    service: {{ .service.name }}
  domainClass: cluster-ingress
{{- if contains "-" .cluster }}
  cluster: {{ .cluster | replace "-" "" }}
{{- else }}
  cluster: {{ .cluster }}
  {{- end }}
  ingressType:
    {{- range .ingressType }}
    - {{ . }}
    {{- end }}
  config:
    {{- if .config }}
    {{ .config | toYaml | nindent 4 | trim }}
    {{- else }}
      upstream-setting:
        proxy-setting:
          protocol: http
          path: /
          connect_timeout: 60000
          retries: 3
          read_timeout: 60000
          write_timeout: 60000
        route-setting:
          methods: "POST,PUT,DELETE,PATCH,GET,OPTIONS"
          preserve_host: false
          strip_path: false
    {{- end }}
---
{{- end }}
{{- end }}
