{{- range .Values.heraclesDomainSpecifications }}
---
{{ include "heracles.domainSpecification" (dict "root" $ "item" .) }}
{{- end }}

{{- range .Values.heraclesDomains }}
---
{{ include "heracles.domain" (dict "root" $ "item" .) }}
{{- end }}

{{- range .Values.heraclesPathRouters }}
---
{{ include "heracles.pathRouter" (dict "root" $ "item" .)}}
{{- end }}

{{- range .Values.heraclesOlympusDomains }}
---
{{ include "heracles.olympusDomain" (dict "root" $ "item" .)}}
{{- end }}

{{- if .Values.heraclesDomainClusterMapper }}
---
{{ include "heracles.domainClusterMapper" (dict "root" $ "item" .Values.heraclesDomainClusterMapper) }}
{{- end }}

{{- if .Values.heraclesClusterProxy }}
---
{{ include "heracles.clusterProxy" (dict "root" $ "item" .Values.heraclesClusterProxy) }}
{{- end }}


{{- range .Values.heraclesClusterRoutes }}
---
{{ include "heracles.clusterRoute" (dict "root" $ "item" .)}}
{{- end }}
