{{- if .Values.HeraclesDomainSpec.enabled }}
{{- range .Values.HeraclesDomainSpec.specifications }}
apiVersion: zeta.tech/v1alpha1
kind: HeraclesDomainSpecification
metadata:
 name: {{ .name }}
 namespace: {{ .namespace }}
spec:
 config: {}
---
{{- end }}
{{- end }}