{{- if .Values.HeraclesPathRouter.enabled }}
{{- range .Values.HeraclesPathRouter.routers }}
apiVersion: zeta.tech/v1alpha1
kind: HeraclesPathRouter
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "default-namespace" }}
spec:
  config: {}
  domain: {{ .domain }}  # Use $ to access outer context
  fallback:
    enabled: true
    upstream: {{ .upstream }}
  loopback: true
  pathPrefix: {{ .pathprefix }}
  paths:
    {{- range .paths }}
    - {{ . }}
    {{- end }}
  tokenDecodeApi: noapi
  upstream: {{ .upstream }}
  upstreamParams: []
---
{{- end }}
{{- end }}
