{{- if .Values.HeraclesDomain.enabled }}
{{- range .Values.HeraclesDomain.domains }}
apiVersion: zeta.tech/v1alpha1
kind: HeraclesDomain
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "zone-traffic" }}
spec:
  domainClass: {{ .domainClass }}
  domainSpec: {{ .spec }}
  hostname:
    {{- range .hostnames }}
    - {{ . | quote }}
    {{- end }}
---
{{- end }}
{{- end }}
